project_name: proaction
release:
  github:
    owner: proactionhq
    name: proaction
builds:
  - id: proaction
    goos:
      - linux
      - windows
      - darwin
    goarch:
      - amd64
      - "386"
    env:
      - CGO_ENABLED=0
    main: cmd/proaction/main.go
    ldflags: -s -w
      -X github.com/proactionhq/proaction/pkg/version.version={{.Version}}
      -X github.com/proactionhq/proaction/pkg/version.gitSHA={{.Commit}}
      -X github.com/proactionhq/proaction/pkg/version.buildTime={{.Date}}
      -extldflags "-static"
    binary: proaction
    hooks: {}
archives:
  - id: proaction
    builds:
      - proaction
    format: tar.gz
    name_template: "{{ .Binary }}_{{ .Os }}_{{ .Arch }}"
    files:
      - licence*
      - LICENCE*
      - license*
      - LICENSE*
      - readme*
      - README*
dockers:
  - goos: linux
    goarch: amd64
    image_templates:
      - "proactionhq/proaction:latest"
      - "proactionhq/proaction:{{ .Major }}.{{ .Minor }}.{{ .Patch }}"
    dockerfile: deploy/Dockerfile

brews:
  - name: proaction
    ids:
      - proaction
    github:
      owner: proactionhq
      name: homebrew-tap
    commit_author:
      name: proactionbot
      email: bots@proaction.io
    folder: Formula
    homepage: "https://proaction.io"
    description: "Build better GitHub Action Workflows"
    skip_upload: false

# snapcrafts:
#   - id: proaction
#     builds:
#       - proaction
#     name_template: "{{ .Binary }}_{{ .Os }}_{{ .Arch }}"
#     name: proaction
#     publish: true
#     summary: "Build better GitHub Action Workflows"
#     description: |
#       Proaction is a CLI that improves your GitHub Action workflows by
#       suggesting changes that will improve reliability and create more
#       reproducible workflow executions.
#     confinement: classic
#     license: Apache-2.0
