name: ""
on:
  - pull_request

jobs:
  terraform:
    name: "simple"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2.2.0

      - name: "simplejs"
        uses: proactionhq/proaction-test-actions@dfcd6a3

      - uses: proactionhq/proaction/action@v0.4.5
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}