name: ""
on:
  - pull_request

jobs:
  terraform:
    name: "simple"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2.1.1

      - name: "simplejs"
        uses: proactionhq/proaction-test-actions@6207cbd

      - uses: proactionhq/proaction/action@v0.4.0
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}