on:
  push:
    branches:
      - action

jobs:
  run-proaction:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2

      - uses: proactionhq/proaction/action@v0.3.2
        with:
          workflow-files: .github/workflows/build-test-deploy.yaml

      - uses: peter-evans/create-pull-request@v2
        with:
          commit-message: "[proaction] updating workflow"
          title: Updating workflow from Proaction
          token: ${{ secrets.PROACTION_TOKEN }}
